version: '2'
services:
  node:
    image: 'node:22'
    user: 'node'
    restart: unless-stopped
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    command: 'npm start'
